<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150213000404 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A95490F70C6");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A958D93D649");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A95490F70C6 FOREIGN KEY (part) REFERENCES famelo_coff_domain_model_part (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A958D93D649 FOREIGN KEY (user) REFERENCES famelo_coff_domain_model_user (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A95490F70C6");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A958D93D649");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A95490F70C6 FOREIGN KEY (part) REFERENCES famelo_coff_domain_model_part (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A958D93D649 FOREIGN KEY (user) REFERENCES famelo_coff_domain_model_user (persistence_object_identifier)");
	}
}