<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150211213526 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("CREATE TABLE famelo_coff_domain_model_access (persistence_object_identifier VARCHAR(40) NOT NULL, page VARCHAR(40) DEFAULT NULL, user VARCHAR(40) DEFAULT NULL, `key` VARCHAR(255) NOT NULL, INDEX IDX_5D81A95140AB620 (page), INDEX IDX_5D81A958D93D649 (user), PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_coff_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, publickey VARCHAR(255) NOT NULL, createdat DATETIME NOT NULL, updatedat DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_coff_domain_model_page (persistence_object_identifier VARCHAR(40) NOT NULL, createdat DATETIME NOT NULL, updatedat DATETIME NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("CREATE TABLE famelo_coff_domain_model_part (persistence_object_identifier VARCHAR(40) NOT NULL, PRIMARY KEY(persistence_object_identifier))");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A95140AB620 FOREIGN KEY (page) REFERENCES famelo_coff_domain_model_page (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A958D93D649 FOREIGN KEY (user) REFERENCES famelo_coff_domain_model_user (persistence_object_identifier)");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_user ADD CONSTRAINT FK_339A4D4D47A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A958D93D649");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A95140AB620");
		$this->addSql("DROP TABLE famelo_coff_domain_model_access");
		$this->addSql("DROP TABLE famelo_coff_domain_model_user");
		$this->addSql("DROP TABLE famelo_coff_domain_model_page");
		$this->addSql("DROP TABLE famelo_coff_domain_model_part");
	}
}