<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150212231816 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A95140AB620");
		$this->addSql("DROP INDEX IDX_5D81A95140AB620 ON famelo_coff_domain_model_access");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access CHANGE page part VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A95490F70C6 FOREIGN KEY (part) REFERENCES famelo_coff_domain_model_part (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_5D81A95490F70C6 ON famelo_coff_domain_model_access (part)");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access DROP FOREIGN KEY FK_5D81A95490F70C6");
		$this->addSql("DROP INDEX IDX_5D81A95490F70C6 ON famelo_coff_domain_model_access");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access CHANGE part page VARCHAR(40) DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_access ADD CONSTRAINT FK_5D81A95140AB620 FOREIGN KEY (page) REFERENCES famelo_coff_domain_model_page (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_5D81A95140AB620 ON famelo_coff_domain_model_access (page)");
	}
}