<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20150211215713 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_coff_domain_model_access CHANGE `key` `key` LONGTEXT DEFAULT NULL");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_user CHANGE publickey publickey LONGTEXT DEFAULT NULL");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE famelo_coff_domain_model_access CHANGE `key` `key` VARCHAR(255) NOT NULL");
		$this->addSql("ALTER TABLE famelo_coff_domain_model_user CHANGE publickey publickey VARCHAR(255) NOT NULL");
	}
}